<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-12-18 18:34
=======
# Generated by Django 3.2.6 on 2021-12-20 05:47
>>>>>>> ee6fcf408446f81603bd3f432b079fd4f0a71251

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('district', models.CharField(default='Kathmandu', max_length=30)),
                ('city', models.CharField(default='Sundarijal', max_length=30)),
                ('profile_pic', models.FileField(default='sample_user.jpg', upload_to='images/profiles')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
