# Generated by Django 3.2.6 on 2022-01-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_service_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/category/images'),
        ),
    ]
