# Generated by Django 3.2.9 on 2022-01-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_service_service_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
