# Generated by Django 3.2.9 on 2022-01-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20220107_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/user.png', upload_to='static/profiles'),
        ),
    ]
