# Generated by Django 3.2.9 on 2022-01-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_service_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
