# Generated by Django 3.2.9 on 2022-01-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
