# Generated by Django 3.2.9 on 2022-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
