# Generated by Django 3.2.1 on 2022-02-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20220217_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='shaswot.png', upload_to='media'),
        ),
    ]
