# Generated by Django 3.2.1 on 2022-02-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='shaswot.png', upload_to='static/profile/images'),
        ),
    ]
