# Generated by Django 3.2.9 on 2022-01-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, default='static/images/nabin.png', null=True, upload_to='static/images'),
        ),
    ]
